Dagens Arbejde.
TordLoefgren/FTCalculator pull request #3
Opened 2023-06-28 07:33 UTC by TordLoefgren

## Tirsdag d. 27 juni - Dagens arbejde

### Oversigt over ændringer:
**ViewModels**
* `ICalculatorViewModel.cs`:
Interface lavet for Viewmodel, således at DI-forespørgsel ikke er en abstract class.

* `CalculatorViewModel.cs`:
Benyttet `private set => SetField(ref _activeOperand, value);`. Denne metode er defineret i `ViewModelBase`.
Gjort alle metoder typestærke og gjort Operator Nullable.

* `CentralViewModel.cs`:
Slettet . 

**Views**
* `CalculatorView.xaml.cs`:
Jeg fik hjælp til at genindføre reference mellem `CalculatorView.xaml` og `CalculatorViewModel.xaml.cs` ved metoden `CalculatorProperty`, som bruges som reference i `MainWindow.xaml` . 

* `CalculatorView.xaml`:
Indført linebreak layout ud fra anvisning.
Specificeret `Mode=OneWay` i mine bindinger i TextBlocks.

**Services**:
* `OperatorConversionService`:
Denne service er som nævnt ikke den mest effektive service, men for øvelsens skyld har jeg tilføjet den som dependency. Desuden kan den nu convertere fra enum til string symbol (f.eks. " + "). 
Denne service har sit eget interface.

* `GenericOperationService`:
Efter foreslag, har jeg nu gjort denne klasse generisk, således at den kan tage imod alle slags tal. Derfor har jeg fjernet fakultetsmetoden, da denne er begrænset til heltal. 
Desuden har jeg tilføjet en metode `ComputeByOperator` som  ud fra et enum vil udføre én af de fire regnemetoder i klassen. Denne service har sit eget interface.

**Diverse**
* `Xunit`: Jeg har lavet tests for hver service, for at øve mig på test-navngivninger.
* Erstattet alle `== null` med `is null` eller `is not null`. 

### Spørgsmål
* Jeg mangler i princippet M i MVVM. Eventuelt kunne jeg lave en CalculatorData-model med de properties som findes i `CalculatorViewModel`?
* Jeg har hørt om `Fluent Assertions` og `Mock` packages i forbindelse med C# unit tests. Er dette noget I benytter, og som ville være en god idé at kende mere til?

2023-06-28 09:20 UTC, pmnforce commented on FTCalculator.Tests/Services/OperatorConversionServiceTest.cs
> +            Assert.Throws<ArgumentException>(() => _operationConversionService.OperatorToSymbolString(null));
Bør være ArgumentNullException?

2023-06-28 10:18 UTC, pmnforce requested changes

2023-06-28 10:20 UTC, TordLoefgren commented
> Mangler main at blive merged ind i FTCalculator/2023-06-27? Det er som om dine ændringer mangler?

Ja, det kan jeg se. Jeg har nu merget main ind i FTCalculator/2023-06-27.

Jeg tror problemet var, at jeg har merged FTCalculator/2023-06-23 ind i main, men har ligeledes dannet branch FTCalculator/2023-06-27 ud fra den første branch. Altså var den både foran og bagud. Håber at dette er løst nu.

Klasserne `GenericOperationService` og `ICalculatorViewModel` er specifikke for FTCalculator/2023-06-27, så hvis de er tilstede burde den være up-to-date :)

2023-06-28 12:25 UTC, runemoennike reviewed
Dine spørgsmål:

"Jeg mangler i princippet M i MVVM. Eventuelt kunne jeg lave en CalculatorData-model med de properties som findes i CalculatorViewModel?": Det kan du godt, men jeg tror ikke det er nødvendigt. Vi bruger modeller hovedsageligt når det er til kommunikation (web service, cli, ...) eller til persistance (når man skal gemme til/hente fra filer, regdb, ...).

"Jeg har hørt om Fluent Assertions og Mock packages i forbindelse med C# unit tests. Er dette noget I benytter, og som ville være en god idé at kende mere til?": Vi bruger NSubstitute. Du kan fint øve dig hvis du har lyst, det er ikke så vigtigt præcis hvilket framework, princippet er det samme.

2023-06-28 12:25 UTC, runemoennike commented on FTCalculator/Services/OperatorConversionService.cs
> +        public Operator StringToOperator(string op)
Bliver den her brugt til noget?

2023-06-28 12:25 UTC, runemoennike commented on FTCalculator/Services/OperatorConversionService.cs
> +        public string OperatorToSymbolString(Operator? op)
Den bør nok ikke være nullable (?) hvis den alligevel kaster en exception på null. Så er det bedre at udnytte det statiske tjek man får, hvor compileren vil advare hvis den får null ind, ud fra princippet om at compile-time fejl er bedre end run-time fejl :)

2023-06-29 10:26 UTC, TordLoefgren commented on FTCalculator/Services/OperatorConversionService.cs
> +        public Operator StringToOperator(string op)
Nej, det bliver den ikke. På et overordnet plan er selve klassen nok også overflødig (udover at konvertere fra Operator til symbol). Den er mest tilstede for at have en undskyldning for at have flere services i spil :)

2023-06-29 10:32 UTC, TordLoefgren commented on FTCalculator/ViewModels/CalculatorViewModel.cs
> +            SetOperatorCommand = new RelayCommand(op => SetOperator(operatorConversionService.StringToOperator(op.ToString())));
Det er godt nok smart med generic classes. Jeg fandt ud af at mit View supplerer en Operator enum direkte til ViewModel, og jeg kan nu koge ovenstående ned til: 

`SetOperatorCommand = new RelayCommand<Operator>(SetOperator);`

2023-06-29 10:51 UTC, runemoennike commented on FTCalculator/Services/OperatorConversionService.cs
> +        public Operator StringToOperator(string op)
Ok :)

2023-06-29 10:52 UTC, TordLoefgren commented on FTCalculator/ViewModels/CalculatorViewModel.cs
> +            SetOperatorCommand = new RelayCommand(op => SetOperator(operatorConversionService.StringToOperator(op.ToString())));
### To spørgsmål til generic relay commands:
* Jeg har endnu ikke fundet en god måde at påføre type constraints på den generiske udgave af min klasse: <br>
`public class RelayCommand<T> : ICommand where T : ?` <br>
Da mine Operator-enums hører til `struct` og ikke til `class`, findes der da en fællesnævner som ville være fornuftig? Indtil videre har jeg udeladt denne constraint.

* Jeg laver explicit type casting af min generiske type i `Execute`:
```csharp 
public void Execute(object? parameter)
{
    if (parameter is not null)
    {
        _execute.Invoke((T)parameter);
    }
} 
```
Er dette en fornuftig måde at håndtere den generiske del af klassen? Bør man stole på at det er skaberen af klassen som supplerer et korrekt object?

2023-06-29 11:13 UTC, runemoennike commented on FTCalculator/ViewModels/CalculatorViewModel.cs
> +            SetOperatorCommand = new RelayCommand(op => SetOperator(operatorConversionService.StringToOperator(op.ToString())));
1) Jeg tror ikke der er nogen grund til at sætte et constraint på. Man vil generelt gerne kunne give alle typer af argumenter med til sin RelayCommand. Hvis du virkelig vil begrænse den til Operator, kunne man have `T : Operator` men så er der ingen grund til at have den som generic :)

2) Der er ingen andre måder at gøre det på, siden den nedarver fra ICommand som foreskriver at parametret skal være `object?`. Jeg er lidt i tvivl om hvorvidt det er fornuftigt at lade være med at kalde Invoke hvis parametret er null. Lige her, hvor du kun bruge det til Operator, er det nok fint. I andre scenarier ville man måske gerne kalde kommandoen selvom CommandParameter var null. Bare til en anden gang.

2023-06-29 11:32 UTC, TordLoefgren commented on FTCalculator/ViewModels/CalculatorViewModel.cs
> +            SetOperatorCommand = new RelayCommand(op => SetOperator(operatorConversionService.StringToOperator(op.ToString())));
Super, tak for opklaring :)

2023-06-30 10:52 UTC, merged